import type { AIConfig, WorkspaceData } from "./types";

const chapterText = `雨从凌晨开始落，雾港像一封被海水泡软的旧信，所有字迹都洇在灰白色的天光里。

沈砚站在防波堤尽头，隔着雨幕望向那座废弃灯塔。十二年前父亲失踪的那个夜晚，灯塔也曾亮过三次——短、长、短，像某种迟到了太久的回答。

手机在口袋里震动。陌生号码只发来一句话：别相信守塔人。

他抬头时，原本熄灭的塔灯忽然划过海面。光束停在他脚边，一只被海浪推上岸的铁盒正安静地躺在那里，盒盖上刻着父亲的名字。`;

export const DEFAULT_AI_CONFIG: AIConfig = {
  baseUrl: "https://api.openai.com/v1",
  apiKey: "",
  model: "gpt-4.1-mini",
  apiMode: "auto",
  temperature: 0.8,
  rememberKey: false,
};

export const DEMO_WORKSPACE: WorkspaceData = {
  project: {
    title: "雾港来信",
    genre: "悬疑 · 都市",
    status: "连载中",
    premise: "记者沈砚回到海雾终年不散的故乡，追查父亲十二年前的失踪案，却发现每封匿名来信都在预告下一位失踪者。",
    theme: "记忆是否比真相更可靠；一个人该如何与家族留下的秘密和解。",
    targetWords: 240000,
    targetChapters: 48,
    writingStyle: "克制、冷峻、富有电影感，重视环境意象与细节伏笔",
    pointOfView: "第三人称限知 · 沈砚",
  },
  ideas: [
    {
      id: "idea-1",
      title: "会改变内容的旧邮戳",
      content: "每当潮水退去，匿名信上的邮戳日期就向前推进一天，暗示寄信人并不处于同一条时间线。",
      tags: ["核心诡计", "时间"],
      favorite: true,
      createdAt: "2026-07-10T05:30:00.000Z",
    },
    {
      id: "idea-2",
      title: "灯塔的第三次闪烁",
      content: "短、长、短并非求救信号，而是旧港口档案中代表“证词已被替换”的内部暗号。",
      tags: ["伏笔", "灯塔"],
      favorite: false,
      createdAt: "2026-07-10T05:42:00.000Z",
    },
    {
      id: "idea-3",
      title: "没有倒影的合影",
      content: "一张家庭合影中，所有人都映在玻璃柜门上，唯独父亲没有。照片可能拍摄于失踪之后。",
      tags: ["视觉线索", "家庭"],
      favorite: true,
      createdAt: "2026-07-10T06:02:00.000Z",
    },
  ],
  world: [
    {
      id: "world-1",
      category: "地点",
      title: "雾港",
      summary: "北方海岸一座因旧航运业衰败的港城，入秋后常有持续数周的海雾。",
      details: "城市被旧港区、山城与新开发区分成三层。潮汐表决定着居民的日常，也决定某些秘密何时会重新出现。",
    },
    {
      id: "world-2",
      category: "地点",
      title: "白屿灯塔",
      summary: "停用十二年的旧灯塔，官方记录称其电路已完全拆除。",
      details: "地下有一条战时修建的潮汐通道，退潮后只开放四十分钟。塔壁内侧刻满历任守塔人的值班记号。",
    },
    {
      id: "world-3",
      category: "势力",
      title: "潮汐档案室",
      summary: "由港务局退休职员秘密维持的民间档案组织。",
      details: "保存官方档案中被删去的事故记录。成员以旧船票作为身份凭证，立场并不统一。",
    },
    {
      id: "world-4",
      category: "规则",
      title: "雾中三原则",
      summary: "雾最浓时不鸣笛、不报真名、不回应身后的脚步声。",
      details: "这是当地渔民的禁忌，也可能是早年走私网络用来避免身份暴露的行为规则。故事始终保留超自然与人为解释的双重可能。",
    },
    {
      id: "world-5",
      category: "历史",
      title: "十二年前的黑潮事故",
      summary: "一艘无登记货轮在白屿外海沉没，官方认定无人员伤亡。",
      details: "同一夜有七名港务人员离职或失踪，沈砚父亲是其中之一。事故卷宗缺少第 17 至 26 页。",
    },
  ],
  characters: [
    {
      id: "char-1",
      name: "沈砚",
      role: "主角",
      age: "31",
      identity: "调查记者，雾港人",
      goal: "查清父亲失踪真相并阻止匿名信预告的案件",
      conflict: "依赖证据，却不断遭遇无法被证实的记忆",
      arc: "从把真相视为唯一救赎，到接受真相也需要承担后果",
      traits: ["谨慎", "固执", "敏锐"],
      color: "#4f46e5",
    },
    {
      id: "char-2",
      name: "林见夏",
      role: "盟友",
      age: "29",
      identity: "地方电台夜间主持人",
      goal: "找回失踪的姐姐，并保护仍在雾港生活的母亲",
      conflict: "掌握关键录音，却隐瞒了自己与匿名信的关系",
      arc: "从控制信息换取安全，到主动公开证据",
      traits: ["冷静", "机敏", "防备心强"],
      color: "#0891b2",
    },
    {
      id: "char-3",
      name: "周启明",
      role: "对手",
      age: "54",
      identity: "现任港务集团董事长",
      goal: "确保新港改造按计划完成，掩埋黑潮事故",
      conflict: "他可能保护过沈砚父亲，也可能亲手安排了失踪",
      arc: "从掌控一切的权威，到被迫面对当年选择的代价",
      traits: ["强势", "圆滑", "念旧"],
      color: "#b45309",
    },
    {
      id: "char-4",
      name: "许伯",
      role: "守门人",
      age: "67",
      identity: "白屿灯塔最后一任守塔人",
      goal: "守住潮汐通道里的秘密，直到合适的人出现",
      conflict: "记忆衰退使他的证词不断变化",
      arc: "从拒绝讲述，到用最后一次值守完成证言",
      traits: ["寡言", "多疑", "守信"],
      color: "#64748b",
    },
    {
      id: "char-5",
      name: "沈川",
      role: "缺席者",
      age: "失踪时 42",
      identity: "前港务工程师，沈砚之父",
      goal: "阻止黑潮事故的证据被永久销毁",
      conflict: "留下的证据互相矛盾，真实立场成谜",
      arc: "通过他人的证词从完美父亲还原为做过艰难选择的普通人",
      traits: ["严谨", "沉默", "理想主义"],
      color: "#7c3aed",
    },
  ],
  relationships: [
    {
      id: "rel-1",
      fromId: "char-1",
      toId: "char-2",
      label: "互相试探的同盟",
      tone: "复杂",
      description: "共同调查失踪案，但林见夏暂未交出完整录音。",
    },
    {
      id: "rel-2",
      fromId: "char-1",
      toId: "char-3",
      label: "调查者与被调查者",
      tone: "对立",
      description: "周启明主动提供帮助，使沈砚更加怀疑其动机。",
    },
    {
      id: "rel-3",
      fromId: "char-1",
      toId: "char-5",
      label: "父子 / 未完成的告别",
      tone: "复杂",
      description: "沈砚对父亲既崇拜又怨恨，调查不断改写童年记忆。",
    },
    {
      id: "rel-4",
      fromId: "char-4",
      toId: "char-5",
      label: "旧日搭档",
      tone: "未知",
      description: "许伯声称最后一次见到沈川是在事故前三天，与档案记录冲突。",
    },
    {
      id: "rel-5",
      fromId: "char-2",
      toId: "char-3",
      label: "隐秘交易",
      tone: "对立",
      description: "周启明曾资助林见夏的电台节目，条件不明。",
    },
  ],
  outline: [
    {
      id: "beat-1",
      act: "第一幕 · 归港",
      title: "匿名信与第一次闪光",
      summary: "沈砚因匿名信回到雾港，发现信中预告的失踪已经发生，并在废弃灯塔看见不可能亮起的光。",
      chapterRange: "第 1—8 章",
      status: "已完成",
    },
    {
      id: "beat-2",
      act: "第二幕 A · 潜流",
      title: "缺失的档案页",
      summary: "调查指向黑潮事故。沈砚与林见夏结盟，在潮汐档案室找到被替换过的事故名单。",
      chapterRange: "第 9—16 章",
      status: "进行中",
    },
    {
      id: "beat-3",
      act: "中点",
      title: "寄信人身份反转",
      summary: "匿名信并非来自单一寄信人；每位收信人都被要求寄出下一封信，沈砚也早已在链条之中。",
      chapterRange: "第 17—24 章",
      status: "待规划",
    },
    {
      id: "beat-4",
      act: "第二幕 B · 失控",
      title: "雾港封锁",
      summary: "新港工程意外打开旧潮道，档案室分裂。沈砚必须在公开真相与保护证人之间选择。",
      chapterRange: "第 25—38 章",
      status: "待规划",
    },
    {
      id: "beat-5",
      act: "第三幕 · 退潮",
      title: "最后一次值守",
      summary: "众人在四十分钟退潮窗口进入灯塔地下，拼合父亲留下的完整证词，并决定谁来寄出最后一封信。",
      chapterRange: "第 39—48 章",
      status: "待规划",
    },
  ],
  chapters: Array.from({ length: 16 }, (_, index) => {
    const number = index + 1;
    const titles = [
      "无风之夜", "退回的信", "旧站台", "雾中来客", "潮痕", "夜间电台", "第七码头", "被删去的人", "回声", "黑潮名单", "暗潮依旧", "雾中的灯塔", "无名来信", "旧码头", "消失的船票", "风声鹤唳",
    ];
    const finished = number <= 11;
    return {
      id: `chapter-${number}`,
      number,
      title: titles[index],
      summary: number === 12 ? "沈砚重返白屿灯塔，收到阻止他相信守塔人的短信，并发现刻有父亲名字的铁盒。" : `${titles[index]}的章节梗概，承接黑潮事故调查主线。`,
      content: number === 12 ? chapterText : finished ? `${titles[index]}正文草稿。\n\n本章已完成，围绕雾港调查主线推进，并留下新的线索。`.repeat(number + 4) : "",
      status: finished ? ("已完成" as const) : number <= 13 ? ("草稿" as const) : ("待生成" as const),
      updatedAt: number === 12 ? "2026-07-10T10:24:00.000Z" : `2026-07-${String(Math.max(1, 10 - index)).padStart(2, "0")}T09:18:00.000Z`,
      outlineBeatId: number <= 8 ? "beat-1" : "beat-2",
      pov: "沈砚",
      targetWords: 4200,
    };
  }),
  issues: [
    {
      id: "issue-1",
      severity: "警告",
      category: "时间线",
      title: "守塔人证词日期不一致",
      description: "第 4 章记录许伯在事故前三天见过沈川，第 11 章口述则为事故当晚。需要确认这是记忆问题还是有意伏笔。",
      location: "第 4、11 章",
      resolved: false,
    },
    {
      id: "issue-2",
      severity: "提示",
      category: "情节",
      title: "第七码头线索尚未回收",
      description: "第 7 章出现的蓝色船票在当前大纲中没有后续落点，可关联到第 15 章。",
      location: "第 7 章",
      resolved: false,
    },
  ],
  materials: [
    {
      id: "material-1",
      type: "伏笔",
      title: "蓝色旧船票",
      content: "票面日期被海水泡掉，只剩座位号 17。计划在第 15 章揭示它属于未登记货轮的接驳船。",
      tags: ["待回收", "第7章"],
      createdAt: "2026-07-08T08:00:00.000Z",
    },
    {
      id: "material-2",
      type: "研究",
      title: "海雾与灯塔可见距离",
      content: "浓雾中强光会形成散射光墙，人物可能看见光却无法判断光源距离，可用于制造空间误导。",
      tags: ["环境", "灯塔"],
      createdAt: "2026-07-08T09:30:00.000Z",
    },
    {
      id: "material-3",
      type: "对白",
      title: "许伯的回答",
      content: "“灯灭了不代表没人值守。有时候，黑暗才是给岸上的人看的信号。”",
      tags: ["许伯", "关键对白"],
      createdAt: "2026-07-09T12:20:00.000Z",
    },
    {
      id: "material-4",
      type: "场景",
      title: "退潮后的地下通道",
      content: "墙面潮线像倒置的城市天际线。远处每隔十秒传来一次水滴声，到第七码头标记处突然停止。",
      tags: ["终局", "氛围"],
      createdAt: "2026-07-10T06:18:00.000Z",
    },
  ],
  versions: [
    {
      id: "version-1",
      chapterId: "chapter-12",
      title: "雾中的灯塔",
      content: chapterText.split("\n\n").slice(0, 3).join("\n\n"),
      createdAt: "2026-07-10T09:42:00.000Z",
      note: "进入灯塔前",
    },
  ],
  canon: {
    revision: 0,
    chapterSummaries: [],
    timeline: [],
    characterStates: [],
    threads: [],
    facts: [],
    lastAuditedChapter: 0,
  },
  automation: {
    phase: "idle",
    brief: "",
    seeds: [],
    targetChapters: 16,
    targetWords: 80000,
    chapterWords: 5000,
    currentChapterNumber: 0,
    currentSegment: 0,
    generatedChapterIds: [],
    usage: {
      requestCount: 0,
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
    },
    maxRequests: 250,
    maxTokens: 5000000,
  },
};
